"""Tests guarding the warehouse/sql/ DDL contracts offline.

Verifies the SQL files exist, are non-empty, and stay idempotent
(IF NOT EXISTS / OR REPLACE) so they are safe to re-run.
03_staging_tables.sql is generated by the ddl_generator.
"""

from pathlib import Path

SQL_DIR = Path(__file__).resolve().parents[1] / "warehouse" / "sql"


def _read_sql(filename: str) -> str:
    path = SQL_DIR / filename
    assert path.exists(), f"{filename} missing in warehouse/sql/"
    return path.read_text()


def test_01_database_warehouse_present_and_substantial():
    content = _read_sql("01_database_warehouse.sql")
    assert content.strip(), "01 must contain DDL"
    assert "CREATE DATABASE IF NOT EXISTS SPA_ANALYTICS" in content
    assert "CREATE WAREHOUSE IF NOT EXISTS SPA_WH" in content
    for schema in ["STAGING", "WAREHOUSE", "MART"]:
        assert f"CREATE SCHEMA IF NOT EXISTS SPA_ANALYTICS.{schema}" in content


def test_02_stage_setup_present_and_substantial():
    content = _read_sql("02_stage_setup.sql")
    assert content.strip(), "02 must contain DDL"
    assert "CREATE FILE FORMAT IF NOT EXISTS" in content
    # Stage uses direct credentials (CREATE OR REPLACE, not IF NOT EXISTS)
    assert "CREATE OR REPLACE STAGE" in content
    # Credential placeholders must be present for loader.py injection
    assert "{AWS_KEY_ID}" in content
    assert "{AWS_SECRET_KEY}" in content


def test_02_csv_file_format_has_expected_params():
    content = _read_sql("02_stage_setup.sql")
    assert "SKIP_HEADER" in content
    assert "FIELD_OPTIONALLY_ENCLOSED_BY" in content
    assert "EMPTY_FIELD_AS_NULL" in content
    assert "NULL_IF" in content
    assert "ERROR_ON_COLUMN_COUNT_MISMATCH" in content


def test_02_stage_url_points_to_raw_prefix():
    """Option A: stage points at raw/ so COPY uses @spa_stage/<table>/."""
    content = _read_sql("02_stage_setup.sql")
    assert "s3://spa-data-platform-dev/raw/" in content


def test_03_staging_tables_cover_all_11_tables():
    """03 must be generated from the live Supabase schema for every table."""
    content = _read_sql("03_staging_tables.sql")
    assert content.strip(), "03 must contain DDL"
    for table in ["treatments", "spa_products", "booking_groups", "booking_logs",
                   "transactions", "completed_items", "members", "gift_cards",
                   "reviews", "spa_consultations", "site_settings"]:
        assert f"CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.{table}" in content