"""Generate Snowflake STAGING DDL from the live Supabase (PostgreSQL) schema.

PRD Rule 3: never invent columns. The staging tables mirror exactly what
inspect_table() returns from the source database.

Pure functions (map_postgres_type, generate_create_table) are testable
offline; only generate_ddl/write_staging_ddl/main touch a live database
(postgres_connector is imported lazily for that reason).
"""

from typing import List, Tuple

from config import settings

POSTGRES_TO_SNOWFLAKE = {
    "uuid": "VARCHAR(36)",
    "character varying": "VARCHAR",
    "text": "VARCHAR",
    "numeric": "NUMBER(38,9)",
    "integer": "NUMBER(38,0)",
    "bigint": "NUMBER(38,0)",
    "smallint": "NUMBER(38,0)",
    "double precision": "FLOAT",
    "real": "FLOAT",
    "boolean": "BOOLEAN",
    "timestamp without time zone": "TIMESTAMP_NTZ",
    "timestamp with time zone": "TIMESTAMP_TZ",
    "date": "DATE",
    "jsonb": "VARIANT",
    "json": "VARIANT",
    "array": "VARIANT",
}


def map_postgres_type(pg_type: str) -> str:
    """Map a PostgreSQL data_type to its Snowflake equivalent.

    Strict by design: an unknown type raises instead of silently producing a
    VARCHAR (PRD Rule 3 — surface schema changes so we extend the map
    consciously).
    """
    normalized = pg_type.strip().lower()
    try:
        return POSTGRES_TO_SNOWFLAKE[normalized]
    except KeyError:
        raise RuntimeError(
            f"Unmapped PostgreSQL type '{pg_type}'. Add it to "
            "POSTGRES_TO_SNOWFLAKE in snowflake/ddl_generator.py"
        )


def generate_create_table(table: str, columns: List[Tuple[str, str]]) -> str:
    """Return a CREATE OR REPLACE TABLE statement for one staging table."""
    if not columns:
        raise RuntimeError(f"Cannot generate DDL for '{table}': no columns found")

    column_lines = [f"    {name} {map_postgres_type(pg_type)}"
                    for name, pg_type in columns]
    return (
        f"CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.{table} (\n"
        + ",\n".join(column_lines)
        + "\n);"
    )


def generate_ddl(conn, tables: List[str]) -> str:
    """Inspect every configured table from the live source and build DDL."""
    from extract import postgres_connector  # lazy: needs a live database

    statements = [
        "-- =============================================================",
        "-- 03_staging_tables.sql",
        "-- Generated by snowflake/ddl_generator.py — do not edit by hand.",
        "-- Re-run the generator whenever the source schema changes.",
        "-- =============================================================",
        "",
    ]
    for table in tables:
        columns = postgres_connector.inspect_table(conn, table)
        statements.append(generate_create_table(table, columns))
        statements.append("")
    return "\n".join(statements)


def write_staging_ddl(path: str) -> str:
    """Connect to Supabase and write the generated DDL to `path`."""
    from extract import postgres_connector  # lazy: needs a live database

    conn = postgres_connector.connect()
    try:
        ddl = generate_ddl(conn, settings.SOURCE_TABLES)
    finally:
        conn.close()

    with open(path, "w") as fh:
        fh.write(ddl)
    return ddl


def main() -> None:
    path = "snowflake/sql/03_staging_tables.sql"
    ddl = write_staging_ddl(path)
    print(f"Generated {path} ({len(settings.SOURCE_TABLES)} tables)")
    for table in settings.SOURCE_TABLES:
        marker = f"TABLE SPA_ANALYTICS.STAGING.{table}"
        print(f"  {table:20s} {'OK' if marker in ddl else 'MISSING'}")


if __name__ == "__main__":
    main()
