-- =============================================================
-- 03_staging_tables.sql
-- Generated by warehouse/ddl_generator.py — do not edit by hand.
-- Re-run the generator whenever the source schema changes.
-- =============================================================

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.treatments (
    id VARCHAR(36),
    slug VARCHAR,
    name VARCHAR,
    short_description VARCHAR,
    full_description VARCHAR,
    price NUMBER(38,0),
    duration VARCHAR,
    category VARCHAR,
    image_url VARCHAR,
    details VARIANT,
    is_featured BOOLEAN,
    featured_order NUMBER(38,0),
    is_active BOOLEAN,
    created_at TIMESTAMP_TZ,
    updated_at TIMESTAMP_TZ,
    price_type VARCHAR
);

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.spa_products (
    id VARCHAR(36),
    slug VARCHAR,
    name VARCHAR,
    short_description VARCHAR,
    full_description VARCHAR,
    price NUMBER(38,0),
    category VARCHAR,
    image_url VARCHAR,
    details VARIANT,
    is_featured BOOLEAN,
    featured_order NUMBER(38,0),
    is_active BOOLEAN,
    created_at TIMESTAMP_TZ,
    updated_at TIMESTAMP_TZ
);

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.booking_groups (
    id VARCHAR(36),
    customer_name VARCHAR,
    customer_phone VARCHAR,
    email VARCHAR,
    created_at TIMESTAMP_TZ
);

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.booking_logs (
    id VARCHAR(36),
    item_type VARCHAR,
    item_name VARCHAR,
    source_page VARCHAR,
    created_at TIMESTAMP_TZ,
    status VARCHAR,
    group_id VARCHAR(36),
    price NUMBER(38,0),
    guest_index NUMBER(38,0),
    scheduled_date TIMESTAMP_TZ,
    notes VARCHAR,
    guest_name VARCHAR,
    treatment_id VARCHAR(36),
    product_id VARCHAR(36)
);

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.transactions (
    id VARCHAR(36),
    customer_name VARCHAR,
    customer_phone VARCHAR,
    total_price NUMBER(38,0),
    source VARCHAR,
    notes VARCHAR,
    created_at TIMESTAMP_TZ,
    updated_at TIMESTAMP_TZ,
    discount_amount NUMBER(38,0),
    gift_card_id VARCHAR(36)
);

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.completed_items (
    id VARCHAR(36),
    transaction_id VARCHAR(36),
    item_name VARCHAR,
    item_id VARCHAR(36),
    price NUMBER(38,0),
    booking_log_id VARCHAR(36),
    created_at TIMESTAMP_TZ
);

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.members (
    id VARCHAR(36),
    name VARCHAR,
    phone VARCHAR,
    email VARCHAR,
    joined_date TIMESTAMP_TZ,
    is_active BOOLEAN,
    created_at TIMESTAMP_TZ,
    updated_at TIMESTAMP_TZ,
    membership_expiry TIMESTAMP_TZ,
    total_visits NUMBER(38,0)
);

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.gift_cards (
    id VARCHAR(36),
    gift_code VARCHAR,
    type VARCHAR,
    gift_value NUMBER(38,0),
    item_id VARCHAR(36),
    item_name VARCHAR,
    sender_name VARCHAR,
    sender_phone VARCHAR,
    recipient_name VARCHAR,
    recipient_phone VARCHAR,
    personal_message VARCHAR,
    physical_card BOOLEAN,
    physical_card_fee NUMBER(38,0),
    order_status VARCHAR,
    expires_at TIMESTAMP_TZ,
    created_at TIMESTAMP_TZ,
    updated_at TIMESTAMP_TZ,
    voucher_status VARCHAR,
    discount_amount NUMBER(38,0)
);

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.reviews (
    id VARCHAR(36),
    booking_group_id VARCHAR(36),
    customer_name VARCHAR,
    rating NUMBER(38,0),
    comment VARCHAR,
    created_at TIMESTAMP_TZ,
    guest_index NUMBER(38,0)
);

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.spa_consultations (
    id VARCHAR(36),
    booking_log_id VARCHAR(36),
    first_visit VARCHAR,
    medical_conditions VARIANT,
    medical_details VARCHAR,
    current_conditions VARIANT,
    current_details VARCHAR,
    medication VARCHAR,
    medication_detail VARCHAR,
    family_history VARCHAR,
    family_history_detail VARCHAR,
    surgery_history VARCHAR,
    surgery_history_detail VARCHAR,
    skin_types VARIANT,
    skin_other VARCHAR,
    body_concerns VARIANT,
    body_other VARCHAR,
    massage_pressure VARCHAR,
    expectations VARCHAR,
    created_at TIMESTAMP_TZ,
    updated_at TIMESTAMP_TZ,
    custom_responses VARIANT
);

CREATE OR REPLACE TABLE SPA_ANALYTICS.STAGING.site_settings (
    id VARCHAR(36),
    key VARCHAR,
    value VARCHAR,
    description VARCHAR,
    updated_at TIMESTAMP_TZ
);
